### ISSUE TITLE
Add a method to show the permitted values for filters

### ISSUE THREAD

**Issue by apdavison** [HumanBrainProject/hbp-validation-client#1]
e.g. what values of "cell_type" do we have in the database?

**Comment by appukuttan-shailesh** [comment]
We have a method `get_attribute_options()` which lists valid values for attributes ([see here](https://github.com/HumanBrainProject/hbp-validation-client/blob/master/hbp_validation_framework/__init__.py#L1519)). Or did I interpret this issue wrong?

**Comment by apdavison** [comment]
ok, sorry, that's what I was looking for.
