### ISSUE TITLE
download_model_instance() should strip off "?bluenaas=true" when generating the local file name

### ISSUE THREAD

**Issue by apdavison** [HumanBrainProject/hbp-validation-client#82]

**Comment by appukuttan-shailesh** [comment]
From here: https://github.com/HumanBrainProject/hbp-validation-framework/issues/228#issuecomment-443750412
Presently, only models stored in public CSCS storage container have acces to bluenaas feature via the model catalog.

So we can make this fix selectively for URLs starting with "https://object.cscs.ch/", i.e. here:
https://github.com/HumanBrainProject/hbp-validation-client/blob/master/hbp_validation_framework/__init__.py#L2127

I suppose we can remove all query parameters, and not just "?bluenaas=true", right @apdavison ?

**Comment by appukuttan-shailesh** [comment]
Implemented in #83
