### ISSUE TITLE
Authentication problem - loading EBRAINS log-in page

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-client#91]
Authentication with Python client gives:
> Exception: Something went wrong loading EBRAINS log-in page. Status code 302

The line:
https://github.com/HumanBrainProject/hbp-validation-client/blob/master/hbp_validation_framework/__init__.py#L305
gives
```
https://iam.ebrains.eu/auth/realms/hbp/protocol/openid-connect/auth?response_type=code&client_id=validation-service-v2&redirect_uri=https%3A%2F%2Fvalidation-v2.brainsimulation.eu%2Fauth&scope=openid+profile+collab.drive+clb.drive%3Aread+clb.drive%3Awrite+group+team+web-origins+role_list+roles+email&state=XXXXX.....XXXXX&nonce=XXXXX.....XXXXX
```
_(XXXXX.....XXXXX used to hide info)_

The problem is independent of the password being correct or incorrect.

I wll test again later today and tomorrow to see if the problem persists.

**Comment by appukuttan-shailesh** [comment]
Problem persists.... needs to be investigated.

**Comment by apdavison** [comment]
I've created a ticket with EBRAINS support

**Comment by apdavison** [comment]
This should now be fixed, please can you check?

The problem arose because the EBRAINS Keycloak server was upgraded, and apparently the new version is stricter about checking the validity of requested scopes, so an invalid scope in the VF API implementation that previously passed silently now triggered an error.

**Comment by appukuttan-shailesh** [comment]
Yes, it works now!
Thanks for looking into this @apdavison .
